#!/usr/bin/python

import sys
import time
import base64
import argparse
import subprocess

import pyxaudio


class Beeper:

    def __init__(self, filename=None):
        if filename is None:
            self.channels = 1
            self.rate = 44100
            self.format = pyxaudio.FORMAT_S16

            self.sound = base64.decodebytes(default_sound)

        else:
            if sys.version_info.major == 2:
                filename = filename.decode(sys.getfilesystemencoding())

            source = pyxaudio.Source(filename)

            self.channels = source.channels
            self.rate = source.rate
            self.format = source.format

            self.sound = b"".join(source)

            source.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        return exc_type is KeyboardInterrupt

    def beep(self):
        sink = pyxaudio.Sink()
        sink.setup(self)
        sink.write(self.sound)
        sink.close()


def period(s):
    if s.endswith("h"):
        return float(s[:-1]) * 3600
    elif s.endswith("m"):
        return float(s[:-1]) * 60
    elif s.endswith("s") or s[-1].isdigit():
        return float(s.rstrip("s"))
    else:
        raise ValueError

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("-w", "--wait", type=period, default=0, metavar="NUM",
                      help="wait NUM seconds before beeping, append `m` for minutes, `h` for hours,"
                      " default is %(default)s")
    parser.add_argument("-i", "--interval", type=period, default=2, metavar="NUM",
                      help="wait NUM seconds between two beeps, default is %(default)s")
    parser.add_argument("-n", "--number", type=int, default=3, metavar="NUM",
                      help="beep NUM of times, default is %(default)s")
    parser.add_argument("-f", "--file", metavar="PATH",
                      help="play this sound file instead of the default one")
    parser.add_argument("argv", nargs=argparse.REMAINDER,
                      help="execute a command-line and beep when ready "\
                           "(one beep for success, 3 beeps for failure)")

    args = parser.parse_args()

    if not args.argv:
        time.sleep(args.wait)

        with Beeper(args.file) as beeper:
            for i in range(args.number - 1):
                beeper.beep()
                time.sleep(args.interval)
            beeper.beep()

    else:
        returncode = 0
        try:
            subprocess.check_call(args.argv)
        except subprocess.CalledProcessError as exc:
            returncode = exc.returncode
            beeps = 3
        else:
            beeps = 1

        with Beeper(args.file) as beeper:
            for i in range(beeps):
                beeper.beep()

        sys.exit(returncode)


default_sound = b"""\
lwDZ/z7+4fv0+Hz1xPE67hrrf+iJ5nzl6uVe6Ebt2fTx/uIJ6RTcH3AqTjQvPQdFN0vBTm1P/Uy/
Rlk8Cy4EHA8GX+1X1Q6/3KrfmZSM84PogS+EsooMlcqiv7PXxyDfs/kzFtowmEaNV79jkWtHb0Jv
/WugZTtce0+TP90tAhtNB+7yTN5hzFK+j7MJrNOnOqfbqUuutrMnuuzBHMvw1eriE/JZA8MVOiXL
MEc5EEB7Rd5JR02iT41QRk+OSy9FPDz0MDMjFBK5/oTs79vnzE6/SLNPqeKhL51Bm9abeZ9dp4qz
sMPJ1/bvHQl2IKc1dUjLWJZmR3F8d7B4bHVfbl9jdFQJQkssPBM59/nbRsOprXmcyY+/h5uEW4Y7
jKeVIaKOsRTEt9lD8tYMhSctPgxQfl16ZoFr12ypahdlSlxQUPhBijLpISkQI/2m6BnVw8UMupyx
jqy1qtKruK7Ysle4Wb+fx+PQj9sh6Ar3aQirGFIlwS/8OMRAH0cRTM5PJFKBUmtQ20u3RAw7gy6V
HcoIiPQS4s7Q98Drsh6n452AlwaUTZNNlrydV6kbuUrNUOYbAnAcZzS4SQ5cjWu3d/x+/392f3J5
Nm6HXrVKLzNYGDn60dsWwGOom5WwhziAAIAAgFODJo5XnJutr8GE2KLx9Qs6J6Q/VlMmYipsg3Fq
cklvdWgjXsVQ7UEaMlIhxA9L/Z7ps9VGxeu4erCLqzmqBqyMr560DLtWwkbKRNNP3ZHoavWOBN4T
HCBQKgszdTp8QDtFrkixSlRLykqCSNVD4zzQMoMk3REf/mXrn9kkySS6N63xohSc5ZhamfCd2qbf
s6nEFdmV8DoK5CFANjFHoVTjXs1lR2lmaS1msF8QVj5JRDlyJkYRTfpL47fPx78Ls12prKICn3Ce
LKEMp7Ovr7qQx3DWTOfZ+SEOiiFjMQc+lUcnTvhRSVN8UrNPzErwQw07NDBBI2kUAQQw8jXiW9W1
yrjBe7oDtXmxC7DTsNazHbm0wL3KUdeC5nr4eQy3HosuFDw4R7NPQ1XFV0ZXC1QqTrZF0DqYLTQe
8wyR+c/l8tQNx+C7fbMZruurs6wfsOK1tL2Mx2jTGuFy8HsBYhRSJs80PEC6SCFOWVCJTxVMokaL
P9Y2VCwYIEMSvAJI8WTetc2bwPe2vbDhrXmuJrLetwS/Vsf40P/baugu9psF7RYVKW44NkSaTHFR
i1ICULVKtkOtO7oyxCiHHfMQBwNu8+jh59BKwxa5ULIcr2Sv0rJGuAe/sMZMz0PZouR68RoAkxCN
IvsyzT8/SRlPNVHfT8xLAEYzP1w3Qy6zI40X3Alz+lzpmteFyOq8v7Q+sG+vArIVt8C9VcWyzTrX
9OHa7S37Dwo6GlUqUDfzQEdHOko5SoZH2kL+PFw2jC5kJcIaiw7fAAnyLuJE06PHSb8Muri3C7i9
ujK/D8Xmy+vTZd166Dj1RQNJEiciTzAOO7ZCM0fcSB1IKEVdQEw6RjMfK5UhVRZmCRL7i+tu24zN
38Jcu+e2NbUVtj25WL7YxGvMRdWO353rW/lwCNYYOCmrNu1AJ0hTTMdNmUwISXFDZzwWNGcqKB9B
EsoD3POW4knSIMURuxa0LrBHr12xHLbpvCnFqM512Y7lLvNSAuISZiTTM7Q/X0jpTWdQ8U+3TChH
7D9UN4wteSIFFiMIvvjn5+bW7shivv+2k7ITsWyyY7aEvCDE88z51izinu6I/O8Lpxy3LFo5xkI1
SdpMzU0CTMdHqUEzOogxtieRHPEPrQHU8bTgE9HdxLy7hLUKsk+xS7O8txq+1sXMzhbZ0uQ28kcB
3hFTI4Myaz5cR2ZNulBKUfxOFEoxQ7U63zCkJdoYcAqM+kzp49dMycu9QLWIr6+s4awPsPW17b1w
x0HSXd726/z6LAuMHBQtQTpWRHNLqE/8UFZP5koLRG07kjGgJowaPA3E/j7vut73z33E67sdtg6z
0LJetYC6vMFgygLUmd426v323wQEFOUjYjHfO65D40h0Sz1LXUj8QrA7JzOrKTkfuxMHBxn5nekA
2inNEsObu7K2d7T6tBe4q70ExY7NHde24YPtrfpBCYUZDymoNZE/10Z7S1RNakzQSL1C9joCMvsn
2RxnEIAC8/Lr4YzSI8Z6vIq1ZLEosL+xNrYkvbHFbs9A2jfmiPNTAucSRSQhM/k+3kfmTfBQ9VAB
TgJIqj/UNd4q6x7lEZsD9vOg4qbR28NMufGxs62rrMiuErRzvOjGptJM37zsCPtZCs8adyxgPJZI
M1FYVh1YflajUXBJZj6xMQwk2BUnB+n3/Oce1+PFobdYreGm+KOMpHuopq8VutjGyNRJ4wfyCQFo
EE8gIDFeQfNNkFZuW9Vc1FqcVS5NvkGFNHMmCBh4CZ76UetR21zK37pAr2+nMKNPosekcaprsxy/
R8w82pPoQvd1BmEWVycaOYpIHlT5W1ZgOmGpXrBYSE9uQzQ2FyhuGScKK/o76f3Wg8QVtXupnqFP
naWcm582piuwQLy2yRjYH+fd9mgHDRkLLFY+Ck3rVxZfnmJrYn5e2FY6TNI/MzLQI8wUEgV59Kji
uM+Avg2xU6cooaOe1J/ApDWtGbh5xPLRGuDz7o7+Mg82IeIz90NRUBxZaF4MYPldN1hRT3JEMDjs
Kv0cTA6w/sLtWtsLydi5N64Spnmhl6B1o/KpMLMzvp3K+dcX5iL1PAWqFmgpJzt9SURUeVv/Xr9e
rVo5U29J9j0dMVUj2hShBXP1COSp0SnBMLSzqr2kgaIJpEGpbrGOu0XHQtT84VLwV/9yD+EgqTLL
QWxNmlVJWmBbsFh9Ut5JpD/+MyonqhmbC9/8Ce3L293K/rx7sjarVKf+pnuqKLGqubbDX8883MHp
1PemBroWLShdOB9Fnk7kVM9XP1csU15MsUM7OSctHCCREmUEPvW25DbT3sMVuH6vQ6pbqNypt64K
tji/M8qa1rjjPfF1/8QOkR+QML8+j0lSUd1VHVfhVJ5PS0gDP8gzLycXGooM9/0V7qHcz8tIvvCz
mayGqNOnr6plsCm4BcK8zaraKehA9nAF/RXKJwE4vkR4Tk1V4VjWWC1V9E7TRto8+TCsI7gV/QYU
99jlI9TzxBy5L7BEqq2nr6jarAqzSbuaxa7R1d6c7G77mQsHHSsucjycR8NPylSDVt1UiFAWSlVB
oTaFKqEd3A/sAMjwmt+iz8XCoLg5sd6syavXrSWylbg9wbHLeNcJ5KvxuQAdEVUizzFZPhRIuU4D
UgtShk8PS3FEsTsrMW4lxxjwCtv7hOuo2gPMWMDLtziym68OsL2yX7crvv7GldFv3WLqgvjNB3wY
JCkEN+VB/UlNT3JRg1BmTSdIoEDZNiwrUh5TEEABJvHv3wvQYsO/udGyo66mrVivPbNuudDBRsyT
2P/ln/R/BHMVBCcnNsdBYUpxULxTlVOcUDlL0UOCOl4vpyKxFIYFRvUJ5DbTnMVcu/WzPq+TrRWv
vrJnuOK/HMkk1NLg7u4r/kkOjh/0LyM9IUf3TYZRElI5UFxMV0ZDPjM0LyilGiYMBv0H7Rjc9cw7
wbC4KrOYsJ6wdbI0tg28EcRIzmja1+c09m4FvhVpJos0ZT97R75MD0+9TldMxEf7QDw4+C1sIrcV
BQgR+YvoAdg4ypy/vbe/st2wprHgtHm6+MHvyjLVs+CN7ab7+QoIG3gp4zNMOtI8WjtsNlMvtSY8
HXsT8wkDARj5uvJb7v/rGOs86zXskO2g7w7ziPc0/N0AJgXWCN0LjQ4VER0TKRQ1FNETKRMlEm4Q
lQ2BCQkFxADV/DT52PXY8vbvYu2Y687qHesd7KPtm+9L8vz1UfpV/hECfQWKCFQL5A1VEG8SwRMe
FHcTMBJtEAcO1gr2BiUDsf9M/Bz5N/ad8x/x7u5s7bnsz+yk7QDvBPHF8wf3svr5/egAtwNbBvYI
cwvpDTcQ4RGjEm0SPhFqD0INwQqtB0UETgGe/gb8nPlw92T1MPMZ8bzvau8L8EDxsfJf9Hf2Xvk1
/ID+mACbAnwEaQaLCNMKygz0DVAOHg6ZDc8MZwtPCZcGLgQ7Am8Adf5l/ET61Pcg9bDyE/F78Lrw
n/Eg81j1Pvgm+139O/8eATsDWAVwB+QJfQxXDiwPPA+YDmYNmgsbCfsFNgMQATP/Xf18+5/5mPdk
9V/z5/EP8cfwQ/Fu8jb0uPag+Qn8B/4GAC4CkQT2BmQJ6QsdDqwPeBBtEHoPxQ1XCzUIMAXBAqgA
g/47/PT5xPdk9ebyy/B77+XuKe9s8JHyd/UF+Rb8bv5tAHUClgSUBmIIXwp1DEMORw9WD1kOjwwh
CggHwgNBAYv//v1P/Lb6cvk++K32zfQx863yVPPk9Br30/n8/Mf/0AEyA0kENgXmBWMGJQdHCHkJ
QgoqCjUJpweYBRUDaQBM/tf8C/yl+2r7OPvW+vf5yfia9+T25Pa09yz5MPus/QwAsQGwAiwDUwNF
A0UDuQO+BAgGQwf+B/YHOgfnBQAEwAHj/5n+1/2E/XT9bf0P/SP8x/o5+ej3SPeJ95X4N/px/OT+
xADpAWACWQI/Aj8CmwKBA9sEcQauBx0IrgeKBtcEmgJxAPv+PP4V/j3+dv53/vT93/xf+9X5t/hT
+LH4wvl3+7P9qv8LAdwBLgIoAgwCQgIAAygEjgXTBoIHZQeXBhwF+wKZALP+Yv2x/JH8x/z4/ML8
7vuS+tr4LvcQ9r31NPaC96f5/Pvz/aH/CQFQAp8DHAW8BnQIQAoMDIgNNg7nDZgMXwp3B7cEXwJ1
AOP+hv02/MX6PPmh9/f1WvQ68/3ytvNA9Zb3KPpK/A/+lv/kABsCTwOSBOUFUQfeCF8KaguhC+4K
WAkQB8wE/wKPAW4Aif+j/oT9MvzA+kf5t/dD9lH1LfXr9X73i/lM+8P8CP4h/xAADAEoAlwDpAQF
BnoHrAgTCUsITgY6A8T/lvy3+UT3fPWC9Db0cfQ09Yz2cvjO+or9iAC9AzIH2Qr3DToQpxE9Eu4R
4RBZD4kNiAtCCbYG5gPYAJL9Gfpd9sbyD/BZ7oPtee007obvM/Eh81L1yfeA+mb9bwClAxYHxwoY
DnwQ/hGhEm0SeBH1DygOLAz4CYsH6wQQAvf+m/vz9zP0GfHw7qDtHe1n7Vvu0++n8cLzHPaz+IL7
k/7ZAWAFMgnTDK0PmxGwEvYSexJNEZwPnw10CyUJsgb5A9wAWf2A+Xn1BvKK79vt3uyo7EXtp+6J
8Kvy8fRn9xT6Av00AMgDvwfMCx8PkBE4ExwULBRXE8cRvg92DfAKKAgaBbcBB/4K+sf14PHw7uPs
o+s366Pr0eyT7rHwA/Oc9ZH46/ul/64D8QdLDA8Q3RK0FI8VehWPFOkSyBBsDuQLIAkQBqcC6/7Y
+nb2HPKe7hXsf+rN6QHqC+vk7FLv/fHY9OT3Ivuq/okCygZtC70PFRNeFaYW9BZWFtgUqxIGEDEN
JArVBkoDe/9q+wz3mPLZ7hHsMepA6U7pU+o67MXup/Gv9Nv3IfuL/jcCMQZzCo0OxBEOFHsVDha+
FaIUvxI1ED0NEAq/BkwDqv/E+5r3TPOX7+zsM+tc6l/qMevF7A7v1fHJ9M/35Poj/qoBgwWqCdIN
LhGFE+kUdhUxFSUUbBINEEINTApABxkExAA0/Uv5DfUJ8d3tn+tG6tXpSeqJ64DtAPDg8vD1Ivl6
/A0A4QMKCFwMHxD2EgEVNxabFhsW0hTQEjMQPA0RCr4GQwN0/1r76/aW8g3vXux46mPpJunD6Snr
Re317wHzSfbB+Xv9fgHRBVQKgA7WEVYUDxbrFuAWARZkFCkScQ9fDP4IUQVTARj9mvgS9CPwAu24
6lDpxOgZ6TPqBeyJ7pXx9PSC+Ef8VQC3BGsJ+g2jEWMUNxYrF0sXpBZAFSoTbBA1DbgJBAYYAuH9
aPmz9HDwG+2k6vzoJOgh6AHpsuor7UTw2vPA98z7/v9kBAsJsw2PEXAUZBaJF+cXgRdSFmAUqhFT
DqgK1AbcArD+QPqI9QHxYO2r6sfotOdy5xfoqekS7CXvoPJj9ln6jP77ApoHLAzSDyMSaBPRE04T
6hG4D88MawnFBSICyf7u+6z5FPhG9xD3Jvdy9+X3jfh2+Z36Dvyv/XL/UwErA9YEOgY/B+IHLwhJ
CD8IBgiDB7MGnAVSBOUCYQG0/+j9IPyT+ln5f/j997b3lveY99b3Xvgy+T/6gfvl/HT+PgAsAgwE
ogXLBosHAwhUCIoIkAhHCKoHxAarBV4E7gI+AUX/Lf0/+7n5pPjc90/3Aff29jH3u/eQ+JH5ufoV
/Jv9a/9cATEDkQRoBdQF+QXZBXYF3AQhBE4DcwKYAbYA6P8//9f+w/7l/hb/Nv9S/2T/dP+S/7T/
zf/o/wcANAByALMA2gDUALAAggBTAC0AEwAKAAsAFgAhACcAKgAkAAYA4f/J/8D/wP+7/7r/vP+6
/7L/nv+T/5X/nv+c/5b/m/+q/7P/u/+8/8D/y//e//3/KABUAHUAgwCBAH0AeQB1AGYAVQBKAD8A
NwAoABoAAQDl/8P/rf+s/7H/sv+p/6X/m/+U/5H/nP+y/8f/3P/u/wAAFwAgACsAMQA1AD4APQA4
AD4ARQBNAEUALAANAOH/wv+n/5//of+l/6b/uP/Y/wAAHwAnACIAEQAGAAAA/f/3/+j/3P/c/+v/
CQAhACAADgABAAYAHwAsAC8AGQDs/7v/l/+V/6D/pf+j/6j/yv8CADUAVwBfAEoAMwAnACQAJwAk
ABsAGQAcACIAMAAwACAA/v/c/8P/pv98/0r/I/8i/zb/Yv+d/+v/LABnAJcAxQDrAPQA5gDEAKEA
iABwAE0AJwD0/8z/uf+6/77/uv+o/5b/hv+H/47/kP+e/7L/yv/v/wgAGQAeABsAFQAZACgAMAAz
AC4ALQApACwAJgAWAAQA/P/4////AgAEAAAA8P/e/83/xP/D/8n/0P/l//7/FwAvADkANgAtACIA
FgAaACYAJgAZAAUA/P/9/wsAHQA1AEgARQAtABMAAgD4//f/5//V/8X/r/+d/5n/pP+7/9f/7/8J
AB0ANwBFAEgAQgBCAEAAOgAoABUAAgDs/9r/xv+2/67/u//N/97/8f8CAA4AFQAbACUAOABDAEAA
KwATAP7/8//w//P/AQAIAAkA/v/8/wEACwAVABYAFgAOAP//9P/q/+X/6v/u//L/AAALABYAHQAZ
ABUADAAKAAgADwAUABMADgANAAsADgAJAAEA/P/5//n//v/+//r/8P/l/93/2v/X/9f/1v/V/9//
7P/1//j/+P/3//7/DAAbACoALwA4AD0ARgBNAFQASwA9ACkAFwABAOb/0P++/7H/tP+4/8n/3//s
//j/AAALABkAHwAfAB4AHAAcABwAGgAVABYAEAAQABQAFwAPAAgA+P/p/+P/4P/h/+D/3//j/+z/
+f8FAA8AEgAQAA8ADgAQABMAFQAPAA0ACQALAAoADAAKAAgABAAFAAQABwACAPz/9v/y/+//7//s
/+z/7v/1//v/AQAFAAoAEAAPABMAEgATABEAEQASABMAEQAPAA4ADAAFAAEA9//z/+z/7P/o/+j/
6v/q/+r/7f/0//j//f8IAA8AFgAgACMAKAApACwAKAAqACUAIwAfABoAFQAOAAUAAAD2/+3/6P/o
/+H/4v/h/+L/5f/n/+3/7v/1//r///8GAA0AFQAdACIAJAAmACoAJwAkACUAIgAdABcAEwANAAsA
AwD7//T/7f/s/+f/5v/j/+X/5v/o/+//8P/2//r/AAAEAAwAEwAaAB8AIwAmACcAJwAmACMAIwAd
ABgAEgANAAoAAgD7//H/8f/s/+z/6P/n/+f/6P/r//H/9P/2//z/AgAGAA0AFAAcAB8AIgAoACQA
KQAnACYAHgAgABgAFAAOAAsAAwD7//f/8f/r/+n/6P/m/+j/7P/r/+v/8//2//r///8EAAwAFAAZ
AB8AIwAoACsAJwApACgAIAAhABwAFQAOAAsAAgD7//X/7v/p/+X/5P/l/+X/5f/r/+r/7v/0//j/
/f8EAAsAFAAZAB0AIwAnACoAKQAoACoAJQAiAB0AGQAOAAoAAgD7//j/7v/r/+X/4v/h/+X/5f/k
/+n/7v/u//b//v8CAAwAEgAWAB8AIgAlACoAKwAsACoAJgAjABwAGAAVAAoABAD+//j/7v/s/+f/
4v/g/+P/4//j/+P/7P/u//L/+/8AAAoADQAUABwAIQAlACcAKgAtACoAJQAkAB8AGQAUAAwABQD+
//b/7v/q/+T/4f/e/97/4v/h/+H/6f/u/+//9/8BAAcADAAVABsAIAAkACgAKQAsACwAJAAlACAA
GgATAA8ACAD9//X/7v/q/+f/4f/f/+H/4f/l/+T/5//r//H/9v///wYADQAUABkAHAAgAB8AIQAb
ABwAFwATABAADQAKAAYABwAEAAMAAgADAAAAAgABAAEAAQAEAAUABQAEAAcACAAIAAoADAALAAwA
DgANAAwADQAOAA0ADwALAAsACgANAAgACAAJAAYABAADAAMAAwADAAIAAwADAAUABwAFAAYABgAJ
AAgACwANAA0ADgAPAA4ADwARABAAEAAQAA4ADgANAA0ACQAIAAgABAADAAMAAwAEAAIAAwADAAMA
CAAHAAgABgAMAAsADAANABAAEAAQAA8AEQAQAA8ADwAQAA8ACwAMAAoACQAGAAYABgACAAIABAAD
AAQABAAEAAQAAwAHAAgABwAGAAwACgAMAA8AEAAPAA8ADwAOAA8ADwAPAA4ADQALAAsADAAJAAYA
CAAFAAIAAgADAAQAAgADAAMAAwADAAYABgAIAAcACgAKAAwADgAPAA4AEAAOAA8ADgAPABAADwAP
AAsACwAKAAkABwAGAAQAAQABAAAAAQACAAEAAAAAAAIABAAEAAUABQAJAAkACQALAA4ADgAOAA0A
CQAJAAoACgALAAoACQAKAAgACAAIAAkACAAIAAgACAAHAAcABwAHAAgACAAIAAcABwAIAAgABwAI
AAgACAAHAAcACAAIAAgACAAIAAgACAAIAAcACAAHAAgACAAHAAgABwAHAAgABwAHAAcABwAIAAcA
CAAIAAcABwAIAAkACQAHAAgACAAIAAgACQAJAAgABwAIAAkACAAIAAgABwAHAAcACAAGAAgABwAI
AAgACAAIAAkABwAIAAkACAAIAAcACAAIAAkACQAHAAkACQAIAAgACAAIAAgABwAGAAkACAAIAAcA
CAAGAAcABwAHAAgABwAHAAgACAAHAAgACQAIAAgACAAJAAgACAAIAAgACQAIAAkACAAIAAcABwAI
AAgABwAIAAgABwAHAAcABwAHAAcACAAIAAcACAAIAAYABwAHAAgABgAHAAgABwAGAAcABwAIAAcA
BwAIAAcABwAIAAcACAAIAAgACAAIAAgABgAGAAgABwAHAAcABwAGAAYABgAGAAcABQAHAAUABgAG
AAYABgAFAAUABQAFAAQABQAFAAcABAAGAAYABgAGAAYABgAGAAYABgAGAAYABgAGAAYABgAHAAYA
BQAFAAUABQAEAAUABQAEAAQABAADAAQABAAFAAQABQAFAAUABAAEAAQABQAFAAQABQAFAAYABgAF
AAQABQA=
"""

if __name__ == "__main__":
    main()

